---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: yes

dotfiles_repo: https://github.com/Joshbarrington/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/github/dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignoreglobal
  - .osx
  - .zshrc
  - .treeignore

homebrew_installed_packages:
  - aws-shell
  - awscli
  - azure-cli
  - asdf
  - bat
  - ccls
  - cmake
  - ctags
  - curl
  - exa
  - fd
  - ffmpeg
  - fswatch
  - fzf
  - fx
  - gh
  - git
  - httpie
  - hub
  - jq
  - mas
  - neovim
  - node
  - openssl
  - ripgrep
  - rename
  - tig
  - tree
  - unzip
  - wget
  - zsh
  - zsh-autosuggestions

homebrew_taps:
  - homebrew/core
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - rectangle
  - firefox
  - google-chrome
  - licecap
  - slack
  - iterm2
  - dash
  - tunnelblick
  - keybase
  - spotify
  - visual-studio-code
  - postman
  - font-fira-code
  - font-firacode-nerd-font
  - maccy
  - vlc
  - xld
  - audio-hijack
  - keycastr
  - beardedspice
  - chromedriver
  - keepassxc
  - signal
  - whatsapp

# See https://github.com/geerlingguy/mac-dev-playbook for below config options.
mas_installed_apps: []
mas_email: ""
mas_password: ""

composer_packages: []

gem_packages: []

npm_packages: []

pip_packages: []

post_provision_tasks: []
